### ISSUE TITLE
Index `DynamicFeeSwapModule` for Base and other chains

### ISSUE THREAD

**Issue by WooSungD** [velodrome-finance/indexer#339]
Currently it is only indexed for Optimism. - example of addition to be made in config
```yaml
  - id: <chainID>
    start_block: 0
    contracts:
      - name: DynamicFeeSwapModule
        address:
          - <address>
```
